# Generated by Django 2.1.3 on 2018-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEdits',
            fields=[
                ('editid', models.FloatField(blank=True, db_column='EditID', primary_key=True, serialize=False)),
                ('ts_edit', models.DateTimeField(blank=True, null=True)),
                ('siteid', models.FloatField(blank=True, db_column='siteID', null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('period_from', models.FloatField(blank=True, null=True)),
                ('period_to', models.FloatField(blank=True, null=True)),
                ('fieldid', models.FloatField(blank=True, db_column='fieldID', null=True)),
                ('ts_editstart', models.DateTimeField(blank=True, db_column='ts_EditStart', null=True)),
                ('ts_editend', models.DateTimeField(blank=True, db_column='ts_EditEnd', null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('newval', models.FloatField(blank=True, db_column='newVal', null=True)),
                ('newvalfloat', models.CharField(blank=True, db_column='newValFloat', max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('groupid', models.CharField(blank=True, db_column='groupID', max_length=255, null=True)),
                ('newval2', models.CharField(blank=True, db_column='newVal2', max_length=255, null=True)),
            ],
            options={
                'db_table': 't_edits',
                'managed': False,
            },
        ),
    ]
